## arty_ddr.xdc — Phase-2 constraints. DDR3 pins come from the MIG core
## (mig.prj); this file covers the fabric-side board pins.
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports sys_clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} [get_ports sys_clk]
set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports sys_rst_n]
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS33} [get_ports UART_0_txd]
set_property -dict {PACKAGE_PIN A9  IOSTANDARD LVCMOS33} [get_ports UART_0_rxd]
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS33} [get_ports UART_0_rtsn]
set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS33} [get_ports UART_0_ctsn]
set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS33} [get_ports UART_0_dtrn]
set_property -dict {PACKAGE_PIN D12 IOSTANDARD LVCMOS33} [get_ports UART_0_dcdn]
set_property -dict {PACKAGE_PIN D13 IOSTANDARD LVCMOS33} [get_ports UART_0_dsrn]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports UART_0_ri]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33} [get_ports UART_0_out1n]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports UART_0_out2n]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33} [get_ports UART_0_baudoutn]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33} [get_ports UART_0_ddis]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports UART_0_txrdyn]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33} [get_ports UART_0_rxrdyn]
set_property -dict {PACKAGE_PIN H5  IOSTANDARD LVCMOS33} [get_ports {gpio_io_o_0[0]}]
set_property -dict {PACKAGE_PIN J5  IOSTANDARD LVCMOS33} [get_ports {gpio_io_o_0[1]}]
set_property -dict {PACKAGE_PIN T9  IOSTANDARD LVCMOS33} [get_ports {gpio_io_o_0[2]}]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o_0[3]}]

## Ethernet (DP83848 MII)
set_property -dict {PACKAGE_PIN D17   IOSTANDARD LVCMOS33} [get_ports {eth_col}]
set_property -dict {PACKAGE_PIN G14   IOSTANDARD LVCMOS33} [get_ports {eth_crs}]
set_property -dict {PACKAGE_PIN F16   IOSTANDARD LVCMOS33} [get_ports eth_mdio_mdc]
set_property -dict {PACKAGE_PIN K13   IOSTANDARD LVCMOS33} [get_ports eth_mdio_mdio_io]
set_property -dict {PACKAGE_PIN G18   IOSTANDARD LVCMOS33} [get_ports {eth_ref_clk}]
set_property -dict {PACKAGE_PIN C16   IOSTANDARD LVCMOS33} [get_ports {eth_rstn}]
set_property -dict {PACKAGE_PIN F15   IOSTANDARD LVCMOS33} [get_ports {eth_rx_clk}]
set_property -dict {PACKAGE_PIN G16   IOSTANDARD LVCMOS33} [get_ports {eth_rx_dv}]
set_property -dict {PACKAGE_PIN D18   IOSTANDARD LVCMOS33} [get_ports {eth_rxd[0]}]
set_property -dict {PACKAGE_PIN E17   IOSTANDARD LVCMOS33} [get_ports {eth_rxd[1]}]
set_property -dict {PACKAGE_PIN E18   IOSTANDARD LVCMOS33} [get_ports {eth_rxd[2]}]
set_property -dict {PACKAGE_PIN G17   IOSTANDARD LVCMOS33} [get_ports {eth_rxd[3]}]
set_property -dict {PACKAGE_PIN C17   IOSTANDARD LVCMOS33} [get_ports {eth_rxerr}]
set_property -dict {PACKAGE_PIN H16   IOSTANDARD LVCMOS33} [get_ports {eth_tx_clk}]
set_property -dict {PACKAGE_PIN H15   IOSTANDARD LVCMOS33} [get_ports {eth_tx_en}]
set_property -dict {PACKAGE_PIN H14   IOSTANDARD LVCMOS33} [get_ports {eth_txd[0]}]
set_property -dict {PACKAGE_PIN J14   IOSTANDARD LVCMOS33} [get_ports {eth_txd[1]}]
set_property -dict {PACKAGE_PIN J13   IOSTANDARD LVCMOS33} [get_ports {eth_txd[2]}]
set_property -dict {PACKAGE_PIN H17   IOSTANDARD LVCMOS33} [get_ports {eth_txd[3]}]
