## arty_ddr.xdc — Phase-2 constraints: UART + LEDs only.
## Clock, reset, and all DDR3 pins are constrained by the board files / MIG.
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS33} [get_ports UART_0_txd]
set_property -dict {PACKAGE_PIN A9  IOSTANDARD LVCMOS33} [get_ports UART_0_rxd]
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS33} [get_ports UART_0_rtsn]
set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS33} [get_ports UART_0_ctsn]
set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS33} [get_ports UART_0_dtrn]
set_property -dict {PACKAGE_PIN D12 IOSTANDARD LVCMOS33} [get_ports UART_0_dcdn]
set_property -dict {PACKAGE_PIN D13 IOSTANDARD LVCMOS33} [get_ports UART_0_dsrn]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports UART_0_ri]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33} [get_ports UART_0_out1n]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports UART_0_out2n]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33} [get_ports UART_0_baudoutn]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33} [get_ports UART_0_ddis]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports UART_0_txrdyn]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33} [get_ports UART_0_rxrdyn]
set_property -dict {PACKAGE_PIN H5  IOSTANDARD LVCMOS33} [get_ports {gpio_io_o_0[0]}]
set_property -dict {PACKAGE_PIN J5  IOSTANDARD LVCMOS33} [get_ports {gpio_io_o_0[1]}]
set_property -dict {PACKAGE_PIN T9  IOSTANDARD LVCMOS33} [get_ports {gpio_io_o_0[2]}]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {gpio_io_o_0[3]}]
