#!/usr/bin/env python3
"""
BitNet ONNX converter for ternarycore.

Two modes:
  1. Real ONNX:  python convert_bitnet_onnx.py model.onnx
  2. Synthetic:   python convert_bitnet_onnx.py --synthetic --rows 4 --cols 4

In either mode, generates:
  - Verilog testbench stimulus for the pipeline RTL
  - Expected output file for verification
  - C++ stimulus header for Verilator tests
"""

import argparse
import json
import sys
from pathlib import Path

# ── Ternary encoding ──────────────────────────────────────────────
# BitNet b1.58 weight encoding (2 bits per weight):
#   00 = 0 (zero)
#   01 = +1 (positive)
#   10 = -1 (negative)
#   11 = invalid

def pack_ternary_weights(weights: list[int], cols: int) -> int:
    """Pack list of ternary values into 2*cols-bit weight_enc word."""
    packed = 0
    for i, w in enumerate(weights[:cols]):
        enc = {0: 0, 1: 1, -1: 2}.get(w, 0)
        packed |= enc << (2 * i)
    return packed


def quantize_activation(value: int, inv: int, precision: int = 15) -> int:
    """Mirror activation_quant.v for one signed activation."""
    shifted = (value * inv + (1 << (precision - 1))) >> precision
    return max(-127, min(127, shifted))


def scale_accumulator(acc: int, alpha: int, precision: int = 15) -> int:
    """Mirror ternary_scale.v's arithmetic shift and remainder rounding."""
    product = acc * alpha
    remainder = product & ((1 << precision) - 1)
    return (product >> precision) + int(remainder != 0)


def verilog_signed_literal(value: int, width: int = 32) -> str:
    """Return a syntactically valid sized signed decimal literal."""
    sign = "-" if value < 0 else ""
    return f"{sign}{width}'sd{abs(value)}"


# ── Test vector generation ─────────────────────────────────────────

def generate_tests(rows: int, cols: int, rng_seed: int = 42):
    """Generate synthetic BitNet test vectors.

    Yields dicts with:
      activations: list of int8 activation values (one per depth/cycle)
      weights: list of [weight_per_col] ternary values (one per depth/cycle)
      alpha:      [alpha_per_col] scale values (Q15)
      inv:        int inverse absmax (precomputed)
      expected:   [expected_per_col] dot product after scale
    """
    import random
    rng = random.Random(rng_seed)

    test_vectors = []

    for row in range(rows):
        depth = cols
        activations = [rng.randint(-50, 50) for _ in range(depth)]
        alphas = [rng.randint(1, 65535) for _ in range(cols)]
        # Per-depth-position weights — each depth position has its own set of col weights
        all_weights = [[rng.choice([-1, 0, 1]) for _ in range(cols)] for _ in range(depth)]

        # Compute absmax for this row
        absmax = max(abs(a) for a in activations) or 1
        inv = round(32768 * 127 / absmax)

        # Compute bit-exact pipeline output: quantize, dot, then Q15 scale.
        quantized = [quantize_activation(a, inv) for a in activations]
        dot_acc = [0] * cols
        for d in range(depth):
            for c in range(cols):
                dot_acc[c] += quantized[d] * all_weights[d][c]
        expected = [
            scale_accumulator(dot, alphas[c])
            for c, dot in enumerate(dot_acc)
        ]

        test_vectors.append({
            "activations": activations,
            "weights": all_weights,  # list of lists: [depth][col]
            "alphas": alphas,
            "inv": inv,
            "absmax": absmax,
            "quantized": quantized,
            "expected": expected,
        })

    return test_vectors


# ── Verilog output ─────────────────────────────────────────────────

def write_verilog_tb(tests, path: Path):
    """Write a Verilog testbench that drives the pipeline."""
    if not tests:
        raise ValueError("at least one test vector is required")

    depth = len(tests[0]["activations"])
    cols = len(tests[0]["alphas"])
    if depth <= 0 or cols <= 0:
        raise ValueError("test vectors must have positive depth and column counts")

    lines = [
        "// Auto-generated by convert_bitnet_onnx.py",
        "`timescale 1ns / 1ps",
        "module tb_bitnet_pipeline;",
        "    reg clk, rst_n, valid_in;",
        "    reg signed [7:0] activation;",
        "    reg [21:0] inv;",
        f"    reg [{cols * 16 - 1}:0] alpha;",
        f"    reg [{cols * 2 - 1}:0] weight_enc;",
        f"    wire [{cols * 32 - 1}:0] result;",
        "    wire valid_out;",
        "    integer errors;",
        "",
        f"    ternary_pipeline #(.VECTOR_LEN({depth}), .COLS({cols})) dut(",
        "        .clk(clk), .rst_n(rst_n),",
        "        .valid_in(valid_in), .activation(activation), .inv(inv),",
        "        .alpha(alpha), .weight_enc(weight_enc),",
        "        .result(result), .valid_out(valid_out)",
        "    );",
        "",
        "    always #5 clk = ~clk;",
        "",
    ]

    # Stimulus
    lines.append("    initial begin")
    lines.append("        $dumpfile(\"tb_bitnet_pipeline.vcd\");")
    lines.append("        $dumpvars(0, tb_bitnet_pipeline);")
    lines.append("        clk = 0; rst_n = 0; valid_in = 0; errors = 0;")
    lines.append("        activation = 0; inv = 0; alpha = 0; weight_enc = 0;")
    lines.append("        repeat (2) @(posedge clk);")
    lines.append("        @(negedge clk); rst_n = 1;")

    for test_index, test in enumerate(tests):
        inv_val = test["inv"]
        alpha_packed = sum(
            a << (16 * c) for c, a in enumerate(test["alphas"])
        )

        for d, act in enumerate(test["activations"]):
            w_packed = pack_ternary_weights(test["weights"][d], len(test["weights"][d]))
            lines.append("        @(negedge clk);")
            lines.append(f"        valid_in = 1; activation = {act}; inv = {inv_val}; "
                         f"weight_enc = {w_packed}; alpha = {alpha_packed};")

        # Wait for pipeline to drain
        lines.append("        @(negedge clk); valid_in = 0;")
        lines.append(f"        fork : wait_for_result_{test_index}")
        lines.append("            begin @(posedge valid_out); end")
        lines.append(f"            begin repeat ({depth + 20}) @(posedge clk);")
        lines.append(
            f'                $fatal(1, "TIMEOUT test {test_index}: valid_out was not asserted"); end'
        )
        lines.append("        join_any")
        lines.append(f"        disable wait_for_result_{test_index};")
        lines.append("        #1;")
        for col, expected in enumerate(test["expected"]):
            expected_literal = verilog_signed_literal(expected)
            lines.append(
                f"        if ($signed(result[{col}*32 +: 32]) !== {expected_literal}) begin"
            )
            lines.append(
                f'            $display("FAIL test {test_index} col {col}: got %0d expected {expected}", '
                f"$signed(result[{col}*32 +: 32]));"
            )
            lines.append("            errors = errors + 1;")
            lines.append("        end")

    lines.append('        if (errors == 0) $display("ALL TESTS PASSED");')
    lines.append('        else $fatal(1, "%0d TEST(S) FAILED", errors);')
    lines.append("        #20 $finish;")
    lines.append("    end")
    lines.append("endmodule")

    path.write_text("\n".join(lines) + "\n")


# ── CLI ────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Convert BitNet ONNX model to ternarycore test vectors"
    )
    parser.add_argument("model", nargs="?", help="Path to .onnx file")
    parser.add_argument("--synthetic", action="store_true",
                        help="Generate synthetic test data")
    parser.add_argument("--rows", type=int, default=4, help="Rows to generate")
    parser.add_argument("--cols", type=int, default=4,
                        help="Columns (dot units)")
    parser.add_argument("--output-dir", "-o", type=Path, default=Path("."),
                        help="Output directory")
    args = parser.parse_args()

    if args.rows <= 0:
        parser.error("--rows must be positive")
    if args.cols <= 0:
        parser.error("--cols must be positive")

    if args.synthetic or not args.model:
        print(f"Generating {args.rows}×{args.cols} synthetic test vectors...")
        tests = generate_tests(args.rows, args.cols)

        args.output_dir.mkdir(parents=True, exist_ok=True)

        # Write Verilog testbench
        tb_path = args.output_dir / "tb_bitnet_pipeline.v"
        write_verilog_tb(tests, tb_path)
        print(f"  Verilog testbench: {tb_path}")

        # Write expected outputs as JSON
        json_path = args.output_dir / "expected_outputs.json"
        json_path.write_text(json.dumps(tests, indent=2, default=str))
        print(f"  Expected outputs:  {json_path}")

        print(f"  {len(tests)} test rows generated.")
        print()
        print("To verify from sim/ with PR #11 applied:")
        print("  iverilog -g2012 -o tb_bitnet_pipeline ../rtl/*.v \\")
        print(f"    {tb_path.resolve()} && vvp tb_bitnet_pipeline")
        return

    # Real ONNX model support (future)
    if args.model:
        print(f"Loading ONNX model: {args.model}")
        try:
            import onnx
            model = onnx.load(args.model)
            onnx.checker.check_model(model)
            print(f"  Model loaded: {model.graph.name}")
            print(f"  {len(model.graph.node)} nodes")
            print()
            print("ONNX parsing for BitNet weights not yet implemented.")
            print("Use --synthetic for now, or contribute the ONNX parser.")
        except Exception as e:
            print(f"Error loading model: {e}", file=sys.stderr)
            sys.exit(1)


if __name__ == "__main__":
    main()
