#!/usr/bin/env python3
"""
weights-to-mem.py -- Convert trained BitNet ternary weights into the memory
formats consumed by the TernaryCore RTL and firmware.

The 2-bit hardware encoding (identical across ternarycore, pqc-secure-element,
and the Arty7 BitNet accelerator) is:

    code 0b00 -> 0   |   0b01 -> +1   |   0b10 -> -1   |   0b11 illegal

Weights are packed LSB-first, 2 bits per weight, N weights per group. This is
exactly the layout used by:
  * tb/tb_ternary_gemm.v   -- W_row[k] = one hex byte, COLS=4 weights, LSB col0
                              (cols (+1,-1,+1,0) -> 0x19)
  * rtl/weight_bram.v      -- 4 weights per byte (Arty7 / feat/bitnet-accelerator)
  * firmware tier1_bench.c -- init_weights() encode_ternary()

OUTPUTS
-------
  --out  file.mem    $readmemh text, `--cols` weights per line (default 4).
  --emit-c-header h  C array `static const unsigned char <name>[]` for firmware
                     BRAM init (drops into tier1_bench.c, replacing synthetics).
  --activations f    Optional: quantize an activation file to int8 two's-complement
                     hex (one per line) for the testbench activation stream.

INPUT
-----
Accepts floats (auto-ternarized via BitNet absmean) or already-ternary values
{-1,0,+1}. Formats: .npy/.npz (numpy) or .csv/.txt (comma/space separated).

USAGE
-----
    python3 weights-to-mem.py --demo
    python3 weights-to-mem.py --in W.npy --out weights.mem --cols 4
    python3 weights-to-mem.py --in W.csv --emit-c-header weights.h --name bitnet_w
    python3 weights-to-mem.py --in W.npy --layout gemm --out gemm.mem
"""

from __future__ import annotations
import argparse
import math
import sys

CODE = {0: 0b00, 1: 0b01, -1: 0b10}


def absmean_scale(values):
    mags = [abs(v) for v in values]
    a = sum(mags) / len(mags) if mags else 0.0
    return a if a > 1e-12 else 1.0


def to_ternary(values, threshold=0.5):
    """If already in {-1,0,1} keep it; else BitNet absmean ternarize."""
    if all(v in (-1, 0, 1) for v in values):
        return [int(v) for v in values]
    alpha = absmean_scale(values)
    return [max(-1, min(1, round(v / alpha))) for v in values]


def load_matrix(path):
    if path.endswith((".npy", ".npz")):
        import numpy as np
        arr = np.load(path)
        if hasattr(arr, "files"):
            arr = arr[arr.files[0]]
        arr = arr.reshape(arr.shape[0], -1) if arr.ndim > 1 else arr.reshape(1, -1)
        return arr.astype(float).tolist()
    rows = []
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith(("#", "//")):
                continue
            sep = "," if "," in line else None
            rows.append([float(x) for x in line.split(sep)])
    return rows


def pack_group(codes):
    """Pack a group of 2-bit codes LSB-first into one hex token."""
    val = 0
    for j, c in enumerate(codes):
        val |= (c & 0b11) << (2 * j)
    nhex = max(1, math.ceil(len(codes) * 2 / 4))
    return format(val, "0{}x".format(nhex))


def to_mem_lines(matrix, layout, cols):
    """Return list of hex strings for $readmemh."""
    coded = [[CODE[t] for t in to_ternary(row)] for row in matrix]
    if layout == "gemm":
        # one packed token per matrix row of `cols` columns (matches tb_ternary_gemm)
        return [pack_group(row[:cols]) for row in coded]
    if layout == "flat":
        # one weight per line, single hex digit (0/1/2) -> 2-bit memory
        return [format(c, "x") for row in coded for c in row]
    # "bytes": flatten, 4 weights/byte (matches weight_bram.v)
    flat = [c for row in coded for c in row]
    per = cols if layout == "group" else 4
    return [pack_group(flat[i:i + per]) for i in range(0, len(flat), per)]


def to_int8_hex(values):
    """Quantize activations to int8 and emit two's-complement 2-hex-digit tokens."""
    out = []
    for v in values:
        iv = max(-128, min(127, int(round(v))))
        out.append(format(iv & 0xFF, "02x"))
    return out


def write_mem(path, lines, header):
    with open(path, "w") as fh:
        fh.write("// {}\n".format(header))
        fh.write("\n".join(lines) + "\n")


def write_c_header(path, name, lines):
    """Emit a C byte array from packed hex tokens (for firmware BRAM init)."""
    byts = [int(tok, 16) for tok in lines]
    with open(path, "w") as fh:
        guard = name.upper() + "_H"
        fh.write("#ifndef {0}\n#define {0}\n".format(guard))
        fh.write("/* Generated by weights-to-mem.py -- TernaryCore */\n")
        fh.write("static const unsigned char {}[] = {{\n".format(name))
        for i in range(0, len(byts), 12):
            chunk = ", ".join("0x{:02x}".format(b) for b in byts[i:i + 12])
            fh.write("    " + chunk + ",\n")
        fh.write("};\n")
        fh.write("#define {}_LEN {}u\n".format(name.upper(), len(byts)))
        fh.write("#endif /* {} */\n".format(guard))


def run(args):
    matrix = load_matrix(args.inp)
    lines = to_mem_lines(matrix, args.layout, args.cols)
    if args.out:
        write_mem(args.out, lines, "TernaryCore weights layout={} cols={}".format(
            args.layout, args.cols))
        print("wrote {} ({} lines) -> $readmemh ready".format(args.out, len(lines)))
    if args.emit_c_header:
        write_c_header(args.emit_c_header, args.name, lines)
        print("wrote {} (C array '{}', {} bytes)".format(
            args.emit_c_header, args.name, len(lines)))
    if args.activations:
        acts = load_matrix(args.activations)
        flat = [v for row in acts for v in row]
        toks = to_int8_hex(flat)
        write_mem(args.act_out or "activations.mem", toks, "int8 activations")
        print("wrote {} ({} activations)".format(args.act_out or "activations.mem", len(toks)))
    if not (args.out or args.emit_c_header or args.activations):
        print("\n".join(lines))


def demo():
    print("=== weights-to-mem.py demo ===")
    # cols (0,1,2,3) = (+1,-1,+1,0) packs to 0x19, matching tb_ternary_gemm.v W_row[0]
    row = [1, -1, 1, 0]
    print("ternary cols (+1,-1,+1,0) -> gemm byte 0x{}  (expect 0x19)".format(
        pack_group([CODE[t] for t in row])))
    matrix = [[0.72, -0.13, 0.55, -0.90], [-0.61, 0.09, -0.77, 0.33]]
    print("\nfloat matrix (absmean ternarized):")
    for layout in ("gemm", "bytes", "flat"):
        print("  layout={:<6}: {}".format(layout, " ".join(to_mem_lines(matrix, layout, 4))))
    print("\nactivations [10,-5,127,-200] -> int8 hex:",
          " ".join(to_int8_hex([10, -5, 127, -200])))


def main(argv=None):
    p = argparse.ArgumentParser(description="TernaryCore weights -> .mem / C header")
    p.add_argument("--in", dest="inp", help="weights file (.npy/.npz/.csv/.txt)")
    p.add_argument("--out", help="output .mem ($readmemh)")
    p.add_argument("--layout", default="gemm", choices=["gemm", "bytes", "flat", "group"],
                   help="gemm=one token/row, bytes=4/byte, flat=1/line, group=cols/token")
    p.add_argument("--cols", type=int, default=4, help="cols per row / per group (default 4)")
    p.add_argument("--emit-c-header", help="also emit a C byte array header")
    p.add_argument("--name", default="bitnet_weights", help="C array name")
    p.add_argument("--activations", help="optional activation file to quantize to int8")
    p.add_argument("--act-out", help="activation .mem output path")
    p.add_argument("--demo", action="store_true")
    args = p.parse_args(argv)

    if args.demo or not args.inp:
        if not args.demo:
            p.print_help()
            print("\n(no --in given; running --demo)\n")
        demo()
        return 0
    run(args)
    return 0


if __name__ == "__main__":
    sys.exit(main())
